name: Lab4 CI-CD Inference

on:
  push:
    branches: [ "main" ]

jobs:
  # =========================
  # JOB 1: TRAIN (CI)
  # =========================
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train model
        run: |
          python scripts/train.py

      - name: Upload model & metrics artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            model/
            metrics.json


  # =========================
  # JOB 2: DEPLOY (CD)
  # =========================
  deploy:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq bc

      - name: Read metrics
        run: |
          echo "MSE=$(jq .mse metrics.json)" >> $GITHUB_ENV
          echo "R2=$(jq .r2 metrics.json)" >> $GITHUB_ENV

      - name: Compare with BEST_MSE
        run: |
          echo "Current MSE: $MSE"
          echo "Best MSE: ${{ vars.BEST_MSE }}"

          if (( $(echo "$MSE >= ${{ vars.BEST_MSE }}" | bc -l) )); then
            echo "${{ github.actor }}----Metric did not improve"
            exit 1
          fi

      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/lab4_wine:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/lab4_wine:${{ github.sha }}

      - name: Update BEST_MSE variable
        run: |
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/BEST_MSE \
            -d "{\"name\":\"BEST_MSE\",\"value\":\"$MSE\"}"
